Implementation of todo list
IT2810/it2810-webutvikling-h18-prosjekt-3-27 pull request #14
Opened 2018-10-05 14:58 UTC by SanderBreivik

Implements #2

Adds a Todo list where users can add, edit, delete and complete tasks. 
Completed tasks are at the bottom of the list, and a progress bar shows the progress of completion.

2018-10-05 15:13 UTC, Artorp requested changes
Looks great! See comments in code.

2018-10-05 15:13 UTC, Artorp commented on components/Todo/TodoScreen.js
> +
Should be called something like TaskPersistence

2018-10-05 15:13 UTC, Artorp commented on components/Todo/TodoScreen.js
> +   */
missing method?

2018-10-05 15:17 UTC, Artorp requested changes

2018-10-05 15:17 UTC, Artorp commented on components/Todo/TodoScreen.js
> +      const taskKeysJson = await AsyncStorage.getItem("TASKKEYS") || "[]";
Maybe move persistence logic to the Task / TaskPersistence class?

2018-10-05 15:21 UTC, Artorp requested changes
Should probably remove debug log statements

2018-10-05 15:21 UTC, Artorp commented on components/Todo/TodoItem.js
> +    console.log(this.props);
Remove debug log

2018-10-05 15:21 UTC, Artorp commented on components/Todo/TodoScreen.js
> +        console.log("taskRes:", tasksResult);
Remove debug log

2018-10-05 15:21 UTC, Artorp commented on components/Todo/TodoScreen.js
> +        console.log("tasks:", tasks);
Remove debug log

2018-10-05 15:44 UTC, SanderBreivik commented on components/Todo/TodoScreen.js
> +      const taskKeysJson = await AsyncStorage.getItem("TASKKEYS") || "[]";
How can i do that when i set the state?

2018-10-05 15:47 UTC, Artorp commented on components/Todo/TodoScreen.js
> +      const taskKeysJson = await AsyncStorage.getItem("TASKKEYS") || "[]";
```js
const tasks = await Task.getAll();
setState({tasks});
```

2018-10-05 16:28 UTC, SanderBreivik commented on components/Todo/TodoScreen.js
> +      const taskKeysJson = await AsyncStorage.getItem("TASKKEYS") || "[]";
Then i'll have to make componentDidMount async, is that allowed?

2018-10-05 16:45 UTC, Artorp commented on components/Todo/TodoScreen.js
> +      const taskKeysJson = await AsyncStorage.getItem("TASKKEYS") || "[]";
No need, you're already calling retrieveTasks which is async

2018-10-05 22:41 UTC, Artorp requested changes

2018-10-05 22:41 UTC, Artorp commented on components/Todo/TodoScreen.js
> +    this.setState({tasks: tasks});
Should set state only if tasks is defined, or make TaskPersistence.retrieveTasks() always return a list

2018-10-05 22:41 UTC, Artorp commented on components/Todo/TodoScreen.js
> +      }
See above comment in componentDidMount, either create a undefined check in componentDidMount, or make this method return an empty array

2018-10-06 09:54 UTC, SanderBreivik commented on components/Todo/TodoScreen.js
> +      }
Solved by check in componentDidMount, thanks for pointing out the bug! 👍

2018-10-06 10:47 UTC, Artorp approved these changes

2018-10-06 10:47 UTC, merged