Change styling of calendar
IT2810/it2810-webutvikling-h18-prosjekt-3-27 pull request #44
Opened 2018-10-17 11:55 UTC by Artorp

Addresses https://github.com/IT2810/it2810-webutvikling-h18-prosjekt-3-27/issues/41

Changes the style of calendar event creation and editing.

2018-10-17 12:01 UTC, SanderBreivik requested changes

2018-10-17 12:01 UTC, SanderBreivik commented on components/Calendar/AddAgendaScreen.js
> +        <Text style={[{
Maybe add styles in StyleSheet to unclutter code?

2018-10-17 12:04 UTC, hellevandenbroek submitted a review, later dismissed
Very nice job. Beautiful colors 💯

2018-10-18 12:56 UTC, SanderBreivik approved these changes

2018-10-18 12:56 UTC, merged